### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by nikhiljha** [nh-99/KhanAcademy-Lesson-Hack#1]
Nothing shows up, unsure what the problem is. :+1:

**Comment by nikhiljha** [comment]
Tried to debug, looks like `questionData` is returning undefined.

Also the "Answers not here" button wasn't showing up so I moved it to a div that actually exists.

I think I'll be able to fix it and PR soon.

**Comment by nh-99** [comment]
The open.call method essentially does a [MITM ](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)and captures all the requests, and from there I grab the only one I care about (the JSON data of the answers). But in all honesty, I'm not really maintaining this anymore because I don't have much of a use for it anymore. If you would like to fix it, that would be awesome and I will definitely pull it in though.

**Comment by nikhiljha** [comment]
Ok I figured it out.

It needs to intercept the call at /api/internal/..../problems/, which means that I should just be able to change the XMLPrototype thing to "problems" - but that doesn't work.

I console.logged everything that the XMLPrototype thing intercepts, and for some reason it's not capturing the call. If I can figure that out I'll have a working version soon.

**Comment by thrawn1080** [comment]
@nikhiljha were you ever able to get the script to work?

**Comment by nikhiljha** [comment]
I can mitm myself and visually see the answers in the JSON, but I don't know how to programmatically do it.

**Comment by thrawn1080** [comment]
Ah okay

**Comment by nh-99** [comment]
Yeah I actually didn't realize it but this script has a fairly big following... I'll put out a patch for it. @nikhiljha if you have any info you can provide to help out, please send it to me at nhgames9@gmail.com Thanks :)

**Comment by Josup** [comment]
if you could patch sometime soon, that would be amazing, and greatly appreciated

**Comment by nikhiljha** [comment]
Alright starting work on this again. I feel like I'll get it this time.

**Comment by 3jinx** [comment]
can someone do a tutorial on how to use this?

**Comment by nikhiljha** [comment]
@nh-99 I fixed the interceptor, but I'm having trouble patching in your changes (mostly because I'm doing this in notepad 👍 since I don't have my actual dev laptop with me).

```
// Uses Emscripten stategy for determining environment
const ENVIRONMENT_IS_REACT_NATIVE = typeof navigator === 'object' && navigator.product === 'ReactNative';
const ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function';
const ENVIRONMENT_IS_WEB = typeof window === 'object';
const ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';

if (ENVIRONMENT_IS_REACT_NATIVE) {
  attach(global);
} else if (ENVIRONMENT_IS_WORKER) {
  attach(self);
} else if (ENVIRONMENT_IS_WEB) {
  attach(window);
} else if (ENVIRONMENT_IS_NODE) {
  attach(global);
} else {
  throw new Error('Unsupported environment for fetch-intercept');
}

function attach(env) {
  // Make sure fetch is avaibale in the given environment
  if (!env.fetch) {
    try {
      require('whatwg-fetch');
    } catch (err) {
      throw Error('No fetch avaibale. Unable to register fetch-intercept');
    }
  }
  env.fetch = (function (fetch) {
    return function (...args) {
      return interceptor(fetch, ...args);
    };
  })(env.fetch);
}

let interceptors = [];

function interceptor(fetch, ...args) {
  const reversedInterceptors = interceptors.reduce((array, interceptor) => [interceptor].concat(array), []);
  let promise = Promise.resolve(args);

  // Register request interceptors
  reversedInterceptors.forEach(({ request, requestError }) => {
    if (request || requestError) {
      promise = promise.then(args => request(...args), requestError);
    }
  });

  // Register fetch call
  promise = promise.then(args => fetch(...args));

  // Register response interceptors
  reversedInterceptors.forEach(({ response, responseError }) => {
    if (response || responseError) {
      promise = promise.then(response, responseError);
    }
  });

  return promise;
}

 function register(interceptor) {
    interceptors.push(interceptor);
    return () => {
      const index = interceptors.indexOf(interceptor);
      if (index >= 0) {
        interceptors.splice(index, 1);
      }
    };
  }
  
function appendAnswer(count, answerType, answer) {
    console.log(answer);
}

register({
    request: function (url, config) {
        // Modify the url or config here
        return [url, config];
    },

    requestError: function (error) {
        // Called when an error occured during another 'request' interceptor call
        return Promise.reject(error);
    },

    response: function (response) {
        if (response.url.match(/https:\/\/www.khanacademy\.org\/api\/internal\/user\/exercises\/.*\/problems/g)) {
			response.json().then(function(data) {  
				/**
				*
				* LOOK
				* HERE
				*
				* :D
				*
				*/
				console.log(data.itemData)
			});
		}
		return response;
    },

    responseError: function (error) {
        // Handle an fetch error
        return Promise.reject(error);
    }
});
```

It should just be copy paste for you from here.

As for @3jinx - it's broken right now.

**Comment by nikhiljha** [comment]
Also note that I took most of that code from fetch-intercept, found here.

https://github.com/werk85/fetch-intercept

**Comment by MnMG** [comment]
Does anyone know when this if ever is going to be available.

**Comment by biswarm22** [comment]
@MnMG I do not think anyone is working on this, it would be great if it were working it really need it

**Comment by SimplyPeace** [comment]
@nikhiljha Have you guys patched this yet?

**Comment by alnesef** [comment]
hey so does this work bow and is their a updated version now? @nikhiljha or @nh-99

**Comment by nikhiljha** [comment]
Solution: Get good at your lessons instead of trying to get past them ;)

Alternatively: Learn how to fix this yourself. It's a pretty good introductory JavaScript reverse engineering problem.
